{
 "title": "Guestbook Overview",
 "tags": [
  "guestbook",
  "kubernetes"
 ],
 "panels": [
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend HTTP Requests (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(apache_accesses_total[1m])",
     "legendFormat": "Requests / sec"
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"(frontend|redis).*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Additional Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  }
 ]
}